services:
  api:
    image: habit-hub-api
    build:
      context: .
      dockerfile: HabitHub/Dockerfile
    env_file: .env
    ports:
      - "5000:8080"
    depends_on:
      - db
      - minio
      - redis
  
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    env_file: .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  minio_data:
  redis_data:
